### ISSUE TITLE
ODPresentation.php fatal error - setSpacingBefore(): Argument #1 ($spacingBefore) must be of type int, float given

### ISSUE THREAD

**Issue by xm74** [PHPOffice/PHPPresentation#830]
I encountered this issue in testing. 
Here is a test file and an error dump.
[Credit Card Number.odp](https://github.com/user-attachments/files/17992848/Credit.Card.Number.odp)

```
PHP Fatal error:  Uncaught TypeError: PhpOffice\PhpPresentation\Shape\RichText\Paragraph::setSpacingBefore(): Argument #1 ($spacingBefore) must be of type int, float given, called in {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php on line 653 and defined in {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Shape/RichText/Paragraph.php:356
Stack trace:
#0 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(653): PhpOffice\PhpPresentation\Shape\RichText\Paragraph->setSpacingBefore()
#1 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(627): PhpOffice\PhpPresentation\Reader\ODPresentation->readParagraph()
#2 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(542): PhpOffice\PhpPresentation\Reader\ODPresentation->loadShapeRichText()
#3 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(236): PhpOffice\PhpPresentation\Reader\ODPresentation->loadSlide()
#4 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(153): PhpOffice\PhpPresentation\Reader\ODPresentation->loadSlides()
#5 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(125): PhpOffice\PhpPresentation\Reader\ODPresentation->loadFile()
#6 {hidden}/presidio.php(413): PhpOffice\PhpPresentation\Reader\ODPresentation->load()
#7 {main}
  thrown in {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Shape/RichText/Paragraph.php on line 356

Fatal error: Uncaught TypeError: PhpOffice\PhpPresentation\Shape\RichText\Paragraph::setSpacingBefore(): Argument #1 ($spacingBefore) must be of type int, float given, called in {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php on line 653 and defined in {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Shape/RichText/Paragraph.php:356
Stack trace:
#0 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(653): PhpOffice\PhpPresentation\Shape\RichText\Paragraph->setSpacingBefore()
#1 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(627): PhpOffice\PhpPresentation\Reader\ODPresentation->readParagraph()
#2 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(542): PhpOffice\PhpPresentation\Reader\ODPresentation->loadShapeRichText()
#3 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(236): PhpOffice\PhpPresentation\Reader\ODPresentation->loadSlide()
#4 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(153): PhpOffice\PhpPresentation\Reader\ODPresentation->loadSlides()
#5 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/ODPresentation.php(125): PhpOffice\PhpPresentation\Reader\ODPresentation->loadFile()
#6 {hidden}/presidio.php(413): PhpOffice\PhpPresentation\Reader\ODPresentation->load()
#7 {main}
  thrown in {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Shape/RichText/Paragraph.php on line 356
```

**Comment by Progi1984** [comment]
This issue has been fixed by a maintainer. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).
