### ISSUE TITLE
PowerPoint97.php fatal error - getStream(): Argument #1 ($stream) must be of type int, null given

### ISSUE THREAD

**Issue by xm74** [PHPOffice/PHPPresentation#831]
One more issue found with the MS PowerPoint presentation.
Here is a test [file](https://eprove.net/test1 SW 2796.ppt) to download and an error dump.

```
PHP Fatal error:  Uncaught TypeError: PhpOffice\Common\Microsoft\OLERead::getStream(): Argument #1 ($stream) must be of type int, null given, called in {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint97.php on line 478 and defined in {hidden}/vendor/phpoffice/common/src/Common/Microsoft/OLERead.php:203
Stack trace:
#0 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint97.php(478): PhpOffice\Common\Microsoft\OLERead->getStream()
#1 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint97.php(451): PhpOffice\PhpPresentation\Reader\PowerPoint97->loadOLE()
#2 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint97.php(439): PhpOffice\PhpPresentation\Reader\PowerPoint97->loadFile()
#3 {hidden}/presidio.php(413): PhpOffice\PhpPresentation\Reader\PowerPoint97->load()
#4 {main}
  thrown in {hidden}/vendor/phpoffice/common/src/Common/Microsoft/OLERead.php on line 203

Fatal error: Uncaught TypeError: PhpOffice\Common\Microsoft\OLERead::getStream(): Argument #1 ($stream) must be of type int, null given, called in {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint97.php on line 478 and defined in {hidden}/vendor/phpoffice/common/src/Common/Microsoft/OLERead.php:203
Stack trace:
#0 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint97.php(478): PhpOffice\Common\Microsoft\OLERead->getStream()
#1 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint97.php(451): PhpOffice\PhpPresentation\Reader\PowerPoint97->loadOLE()
#2 {hidden}/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint97.php(439): PhpOffice\PhpPresentation\Reader\PowerPoint97->loadFile()
#3 {hidden}/presidio.php(413): PhpOffice\PhpPresentation\Reader\PowerPoint97->load()
#4 {main}
  thrown in {hidden}/vendor/phpoffice/common/src/Common/Microsoft/OLERead.php on line 203
```

**Comment by megamisan** [comment]
I got this issue too. My steps to reproduce :
1. Programmatically create a presentation with a single slide, containing a single text in it, in OOXML format;
2. Convert it to PowerPoint97 format using LibreOffice;
3. Try to load it.

If fails because there is no picture in the file. The stream is not mandatory.

Edit: Saw the issue also with a clean file created using MS PowerPoint.
